version: '3.8'

volumes:
  alumni_volume:

services:
  database:
    container_name: db
    ports: 
      - "5432:5432"
    build:
      context: ./pg
    image: "postgres:latest"
    restart: always
    volumes:
      - alumni_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "9499"
      POSTGRES_DB: "alumniNWS"
      PGPORT: "5432"
      POSTGRES_USER: "postgres"
  php:
    container_name: php
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www/Alumni-Back
    depends_on:
      - database
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '31415:80'
    volumes:
      - ./:/var/www/Alumni-Back
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database