name: Symfony

on:
  push:
    branches:
    - main

jobs:
  symfony-tests:
    runs-on: ubuntu-latest
    steps:
    #  To automatically get bug fixes and new Php versions for shivammathur/setup-php,
    # change this to (see https://github.com/shivammathur/setup-php#bookmark-versioning):
    # uses: shivammathur/setup-php@v2
    - uses: actions/checkout@v3
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
    - name: Check PHP Version
      run: php -v

    - name: Setup Redis with zhulik/redis-action
      uses: zhulik/redis-action@1.1.0
      with:
        redis version: '5'
        
    - uses: harmon758/postgresql-action@v1
      with:
        postgresql version: '13'
        postgresql db: 'alumniNWS'
        postgresql user: 'postgres'
        postgresql password: '9499'
      
    - name: Install composer require symfony/runtime
      run: composer require symfony/runtime

    - name: Create the test database
      run: php bin/console --env=test doctrine:database:create

    - name: Create schema for test database
      run: php bin/console --env=test doctrine:schema:create

    - name: Load Doctrine fixtures
      run: php bin/console --env=test doctrine:fixtures:load

    - name: Run functionnal and unit tests
      run: php bin/phpunit

    - uses: actions/checkout@v3
    - uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "alumni-nws-api" #Must be unique in Heroku e
        heroku_email: "AlumniNWS2022@gmail.com"
        usedocker: false




